languageCode: "en-us"
baseUrl: ""
title: "hexyoungs blog"
theme: "anubis"
paginate: 10

menu:
  main:
  - identifier: archive
    name: 归档
    title: Archive
    url: /posts/
    weight: 0

params:
  author: "chux0519"
  description: "杂七杂八"
  images:
    - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "static" directory
  dateFormat: "2006-01-02"
