on: push
name: Build and deploy on push
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: gh-pages
        BUILD_FLAGS: -u https://hexyoungs.github.io
        TOKEN: ${{ secrets.TOKEN }}

  deploy:
    uses: chux0519/zola-scp-action@master
    with:
      local: public/ # eg: dist/*
      remote: ${{ secrets.REMOTE }} # eg: /home/github-action/www
      host: ${{ secrets.HOST }} # eg: example.com
      port: 22
      user: ${{ secrets.USER }} # eg: github-action
      key: ${{ secrets.KEY }} # eg: -----BEGIN OPENSSH PRIVATE KEY-----\nHEIiyzh5cT7hN...
